---
title: "Binary choice experiment"
author: "Liang Zhou"
date: "September 19, 2022"
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 4
    theme: cosmo
    highlight: tango
---

# Load packages 

```{r load-packages, message=F}
library("Hmisc")
library("magick")
library("tidyjson")
library("tidyverse")
library("patchwork")
library("ggrepel")
library("knitr")
library("grid")
```

```{r}
theme_set(theme_bw())
```

# Load trajectories

```{r}
data_path = "../data/"
file.name = "pilot_v3.json"
df.tmp = read_json(file.path(data_path, file.name)) %>% 
  as.tbl_json %>% 
  gather_array("ix") %>%
  gather_object("trial_data")

df.trial_metadata = df.tmp %>% 
  filter(trial_data == "config") %>% 
  gather_object("labels")

  select(-document.id) %>% 
  as_tibble() %>% 
  rename(trial = ix) %>% 
  pivot_wider(names_from = "trial_data", values_from = "value")

df.trial_pointerdata = df.tmp %>% 
  filter(trial_data == "data") %>% 
  gather_array("trial_idx") %>% 
  gather_object("info") %>% 
  select(-trial_data, -document.id) %>% 
  append_values_string("value") %>% 
  group_by(trial_idx) %>% 
  filter(any(value[info == "error"] == "0"),
         any(value[info == "set"] == "main"),
         any(value[info == "type"] == "probe")) %>% 
  ungroup() %>%
  as.tbl_json(json.column = "..JSON") %>% 
  filter(info == "pointer_data") %>% 
  gather_object("pointer_data") %>% 
  gather_array("timestep") %>% 
  append_values_number("value") %>% 
  as_tibble() %>% 
  select(-info) %>% 
  pivot_wider(names_from = "pointer_data", values_from = "value") %>% 
  filter(moving == 1)


  group_by(ix)
  filter(any(value[trial_data == "error"] == 0),
         any(value[trial_data == "set"] == "main")) %>% 
  ungroup() %>%
  filter(trial_data == "pointer_data") %>%
  as.tbl_json(json.column = "..JSON") %>% 
  # select(-document.id, -trial_data, -value) %>% 
  gather_object("value_type") %>% 
  gather_array("step") %>% 
  append_values_number("value") %>% 
  as_tibble() %>% 
  pivot_wider(names_from = "value_type", values_from = value)


df.plot = df.trial_pointerdata
ggplot(df.plot, aes(x = x, y = y, color = factor(ix))) + 
  scale_y_reverse() +
    geom_point(alpha = .6)
    # facet_wrap(~day, scales = "free_x")
```


```{r}
df.plot = df.trial_pointerdata %>% 
  filter(ix == 6)
ggplot(df.plot, aes(x = cx, y = cy, color = factor(trial_idx))) + 
  scale_y_reverse() +
  geom_point(alpha = .6, show.legend=F)
```


